### ISSUE TITLE
Using a dynamic secret

### ISSUE THREAD

**Issue by litenull** [cinch-financial/mongoose-encryption#9]
Hello,

This is a very cool plugin. However, I am wondering if this scenario I will iterate is possible with this plugin.
Lets say, I provide the secret within the request parameter, and I'd like to store a payload in the database on-the-fly with this secret. Each request has its own secret and payload. Is it possible to store data with different secrets within the same collection, and then query one payload with its secret ?

What I'm trying to achieve is complete un-awareness of any key information by the database. Each user stores data with their keys. Is this possible ?

**Comment by joegoldbeck** [comment]
That’s a really interesting scenario! Currently the keys are static per-collection. At some point, the plugin may allow multiple keys per collection (primarily for key rotation), but this would still entail a finite set of keys, all of which would be known to the app.

At the moment I can’t think of anyway to neatly integrate such a feature as dynamic keys passed in with each payload, but if you have any ideas I’d be happy to discuss!

You haven’t told me your use case, but it sounds like you want a security model in which the user doesn’t even need to trust your server environment. Have you considered encrypting and decrypting the most sensitive parts of your payload client-side so they are never exposed to the server? If there are parts of the document that the server needs to access, they could be left unencrypted client-side and, if it works for your use case, the document as a whole (or in part) could then be encrypted and authenticated server-side to protect these other fields.

**Comment by litenull** [comment]
That is a good approach. I could indeed encrypt/decrypt the data on client, without even touching the database. And I could encrypt non-sensitive data with this plugin.

Brilliant, thanks!

However, I've been playing around with the plugin already, and exposing useDynSecret option to the plugin, which allows to specify secret within the mongoose query itself, or on save. But its probably a false approach, since it involves passing the secret in the transport.

**Comment by joegoldbeck** [comment]
Awesome. If you think of it / would like to, let me know what you come up with!

**Comment by BDiehr** [comment]
@litenull Just curious, what did you end up doing? How did it work out for you? I'm curious to hear about it sense I have a similar use case as you.

**Comment by litenull** [comment]
Hey @BDiehr 

What i did is i used NaCl library, and do encryption only on client. Then I store public key and payload in database. When you need the data, you fetch the encrypted payload, and unlock it on client.

Very simple and no key data is transmitted
